name: Deploy to Koyeb

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        lfs: true  # Pulls Git LFS files

    - name: Set up Python 3.12.4
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.4"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download NLTK wordnet
      env:
        NLTK_DATA: /home/runner/nltk_data
      run: |
        mkdir -p $NLTK_DATA
        python -c "import nltk"
        python -m nltk.downloader -d $NLTK_DATA wordnet
        python -m nltk.downloader -d $NLTK_DATA stopwords
        python -m nltk.downloader -d $NLTK_DATA averaged_perceptron_tagger_eng

    - name: Install and configure the Koyeb CLI
      uses: koyeb-community/koyeb-actions@v2
      with:
        api_token: "${{ secrets.KOYEB_API_KEY }}"

    - name: Build and deploy the application
      uses: koyeb/action-git-deploy@v1
      with:
        app-name: magical-movie-search
        service-env: "PORT=8000"
        service-ports: "8000:http"
        service-routes: "/:8000"
        skip-cache: true
        service-instance-type: free
